sudo: required
language: shell
services:
- docker
before_install:
- docker build -t "aaronbbrown/dnsblast:$TRAVIS_BRANCH" .
after_success:
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin && docker push aaronbbrown/dnsblast
